import type { Product, Banner, FinancialRecord } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation",
    priceCents: 149990,
    currency: "BRL",
    images: ["/premium-wireless-headphones.png"],
    categoryId: "cat-1",
    stock: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
    sku: "PWH-001",
    slug: "premium-wireless-headphones",
    category: {
      id: "cat-1",
      name: "Electronics",
      slug: "electronics",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
  {
    id: "2",
    title: "Smart Watch Pro",
    description: "Advanced smartwatch with health tracking features",
    priceCents: 199990,
    currency: "BRL",
    images: ["/smart-watch-pro.jpg"],
    categoryId: "cat-1",
    stock: 30,
    createdAt: new Date(),
    updatedAt: new Date(),
    sku: "SWP-001",
    slug: "smart-watch-pro",
    category: {
      id: "cat-1",
      name: "Electronics",
      slug: "electronics",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
  {
    id: "3",
    title: "Designer Leather Jacket",
    description: "Premium leather jacket with modern design",
    priceCents: 249990,
    currency: "BRL",
    images: ["/designer-leather-jacket.jpg"],
    categoryId: "cat-2",
    stock: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
    sku: "DLJ-001",
    slug: "designer-leather-jacket",
    category: {
      id: "cat-2",
      name: "Fashion",
      slug: "fashion",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
  {
    id: "4",
    title: "Minimalist Desk Lamp",
    description: "Modern LED desk lamp with adjustable brightness",
    priceCents: 39990,
    currency: "BRL",
    images: ["/minimalist-desk-lamp.png"],
    categoryId: "cat-3",
    stock: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
    sku: "MDL-001",
    slug: "minimalist-desk-lamp",
    category: {
      id: "cat-3",
      name: "Home & Garden",
      slug: "home-garden",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
]

export const mockBanners: Banner[] = [
  {
    id: "1",
    imageUrl: "/summer-fashion-collection.png",
    targetUrl: "/products",
    position: 1,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    imageUrl: "/modern-electronics.png",
    targetUrl: "/products?category=Electronics",
    position: 2,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockFinancialRecords: FinancialRecord[] = [
  {
    id: "1",
    type: "receivable",
    description: "Product sales - Week 1",
    amount: 75000,
    category: "Sales",
    date: new Date("2025-01-15"),
    status: "paid",
  },
  {
    id: "2",
    type: "payable",
    description: "Office rent - January",
    amount: 15000,
    category: "Rent",
    date: new Date("2025-01-01"),
    status: "paid",
  },
]
